mesosmaster1:
  hostname: mesosmaster1
  image: mesosphere/mesos:0.24.0-1.0.27.ubuntu1404
  entrypoint: [ "mesos-master" ]
  ports: [ "5050:5050" ]
  environment:
  - MESOS_HOSTNAME=mesosmaster1
  - MESOS_PORT=5050
  - MESOS_LOG_DIR=/var/log/mesos
  - MESOS_QUORUM=1
  - MESOS_REGISTRY=in_memory
  - MESOS_WORK_DIR=/var/lib/mesos
  - MESOS_ROLES=public
mesosslave:
  hostname: mesosslave
  privileged: true
  image: mesosphere/mesos-slave-dind:0.2.2_mesos-0.24.0_docker-1.8.2_ubuntu-14.04.3
  ports: [ "10248","10249" ]
  entrypoint:
  - bash
  - -xc
  - >
    NAME=$$(cut -f2 -d/ <<<$${MESOSMASTER1_NAME}) &&
    N=$${NAME##*_} &&
    PUBLIC_RESOURCES="$$(if [ $${N} = 2 ]; then echo ";cpus(public):2;mem(public):640;ports(public):[7000-7999]"; fi)" &&
    DOCKER_NETWORK_OFFSET=$$(if [ "${CONTAINER_IPS}" = "true" ]; then echo 0.0.$${N}.0; fi)
    exec wrapdocker mesos-slave
    --work_dir="/var/tmp/mesos/$${N}"
    --attributes="rack:$${N};gen:201$${N}"
    --hostname=$$(getent hosts mesosslave | cut -d' ' -f1 | sort -u | tail -1)
    --resources="cpus:4;mem:1280;disk:25600;ports:[8000-21099]$${PUBLIC_RESOURCES}"
  command: []
  environment:
  - MESOS_MASTER=mesosmaster1:5050
  - MESOS_PORT=5051
  - MESOS_LOG_DIR=/var/log/mesos
  - MESOS_LOGGING_LEVEL=INFO
  - MESOS_SWITCH_USER=0
  - MESOS_CONTAINERIZERS=docker,mesos
  - MESOS_ISOLATION=cgroups/cpu,cgroups/mem
  - VAR_LIB_DOCKER_SIZE=10
  - DOCKER_DAEMON_ARGS
  links:
  - mesosmaster1
